[gcp_service_account]
type = "service_account"
project_id = "your project id"
private_key_id = "your private key id"
private_key = "your private key"
client_email = "your client email"
client_id = "your client id"
auth_uri = "your Google cloud auth uri"
token_uri = "you Google cloud token uri"

auth_provider_x509_cert_url = "your cert url (auth)"
client_x509_cert_url = "your x509 cert url (client)"
universe_domain = "your universe domain"
[sheets]
spreadsheet_name = "your spreadsheet name"